//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRoom
    {
        public int id { get; set; }
        public Nullable<int> CustomerIdfk { get; set; }
        public Nullable<int> RoomIdfk { get; set; }
        public Nullable<bool> IsPase { get; set; }
        public string startDate { get; set; }
        public string EndData { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Room Room { get; set; }
    }
}
