//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> Shift { get; set; }
        public Nullable<System.DateTime> JoiningData { get; set; }
        public Nullable<double> Salary { get; set; }
        public string IdCardNumber { get; set; }
        public Nullable<int> IdCardTypeFk { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public Nullable<int> EmployementTypeFk { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string password { get; set; }
    
        public virtual CardType CardType { get; set; }
        public virtual EmployementType EmployementType { get; set; }
        public virtual ShiftType ShiftType { get; set; }
    }
}
